### ISSUE TITLE
Second sync fails

### ISSUE THREAD

**Issue by zeroone82** [Programmierus/ldap-mailcow#12]
I've been trying to get this working and I have been able to get an initial sync at least. It will add my one test user, but then it fails on the second sync:

```
mailcowcustomized_ldap-mailcow | 25.09.20 16:37:50 Config file conf/dovecot/ldap/passdb.conf unchanged
mailcowcustomized_ldap-mailcow | 25.09.20 16:37:50 Config file conf/dovecot/extra.conf unchanged
mailcowcustomized_ldap-mailcow | 25.09.20 16:37:50 Config file conf/sogo/plist_ldap unchanged
mailcowcustomized_ldap-mailcow | 25.09.20 16:37:50 Added Mailcow user: testuser@mydomain.local (Active: True)
mailcowcustomized_ldap-mailcow | 25.09.20 16:37:50 Activated testuser@mydomain.local in filedb
mailcowcustomized_ldap-mailcow | 25.09.20 16:37:50 Sync finished, sleeping 15 seconds before next cycle
mailcowcustomized_ldap-mailcow | Traceback (most recent call last):
mailcowcustomized_ldap-mailcow |   File "syncer.py", line 181, in <module>
mailcowcustomized_ldap-mailcow |     main()
mailcowcustomized_ldap-mailcow |   File "syncer.py", line 31, in main
mailcowcustomized_ldap-mailcow |     sync()
mailcowcustomized_ldap-mailcow |   File "syncer.py", line 54, in sync
mailcowcustomized_ldap-mailcow |     (api_user_exists, api_user_active, api_name) = api.check_user(email)
mailcowcustomized_ldap-mailcow |   File "/api.py", line 66, in check_user
mailcowcustomized_ldap-mailcow |     if 'active_int' not in rsp and rsp['type'] == 'error':
mailcowcustomized_ldap-mailcow | KeyError: 'type'
mailcowcustomized_ldap-mailcow exited with code 1
```

This a very basic user, has a username, first and last name and nothing else. Should I add another field too?

My docker-composer setup is:

```
ldap-mailcow:
      image: programmierus/ldap-mailcow
      network_mode: host
      container_name: mailcowcustomized_ldap-mailcow
      depends_on:
          - nginx-mailcow
      volumes:
          - ./data/ldap:/db:rw
          - ./data/conf/dovecot:/conf/dovecot:rw
          - ./data/conf/sogo:/conf/sogo:rw
      environment:
          - LDAP-MAILCOW_LDAP_URI=ldap://my.ad.IP
          - LDAP-MAILCOW_LDAP_BASE_DN=OU=TestMail,DC=mydomain,DC=local
          - LDAP-MAILCOW_LDAP_BIND_DN=CN=Administrador,CN=Users,DC=mydomain,DC=local
          - LDAP-MAILCOW_LDAP_BIND_DN_PASSWORD=mypassword
          - LDAP-MAILCOW_API_HOST=http://mailcow.localip
          - LDAP-MAILCOW_API_KEY=MY-MAILCOW-KEY
          - LDAP-MAILCOW_SYNC_INTERVAL=15
```
